### ISSUE TITLE
Working AKS config?

### ISSUE THREAD

**Issue by richeney** [jelledruyts/InspectorGadget#1]
Hi @jelledruyts! Great container, and I'm using it extensively in <https://www.azurecitadel.com/network/privatelink/vnetintegration/>. Love it.

I'm trying to get it working in AKS with AGIC enabled. As a container can it work in that environment? Here is my inspectorgadget.yaml:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: inspectorgadget-pod
  labels:
    app: inspectorgadget
spec:
  containers:
  - image: "jelledruyts/inspectorgadget:latest"
    name: inspectorgadget
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: inspectorgadget-service
spec:
  selector:
    app: inspectorgadget
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: inspectorgadget-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /inspectorgadget/
        backend:
          serviceName: inspectorgadget-service
          servicePort: 80

---
```

Any ideas why that isn't working for me?

**Comment by jelledruyts** [comment]
I've deployed it in AKS before (see [here](https://github.com/jelledruyts/Playground/blob/master/AKS/ig-front-end.yaml) for example) and it's "just" a container so it should work anywhere. What I haven't actually tried is put it on a sub-path in the URL as you're doing with the route to "/inspectorgadget/" so not sure if that would cause a problem, although the app should be generating relative URL's as far as I know. That being said, what _is_ the problem you're facing actually? :-)

**Comment by richeney** [comment]
Hi Jelle, and thanks for replying with the example. 

I got it working - the AGIC does not allow the same port used as a listener on both the private and public frontend. I had an existing app on port 80 on the private. I switched that one to port 8080.

I reapplied the inspectorgadget.yaml and the app sprang to life a couple of minutes later once the backend pool, rule and listener came up.

For reference, here is my final inspectorgadget.yaml:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: inspectorgadget-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: inspectorgadget-service
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: inspectorgadget-service
spec:
  selector:
    app: inspectorgadget
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspector-gadget
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inspectorgadget
      tier: front-end
  template:
    metadata:
      labels:
        app: inspectorgadget
        tier: front-end
    spec:
      containers:
      - name: inspectorgadget
        image: jelledruyts/inspectorgadget
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
          name: http
        env:
        - name: tier
          value: "Front End"
        - name: InfoMessage
          value: "You're on the Front End tier"
        - name: BackgroundColor
          value: "#fbfbfb"
---
```

And here are the additional annotations for the "internal" app test to create the 8080 listener on the private front end:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aspnetapp-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "true"
    appgw.ingress.kubernetes.io/override-frontend-port: "8080"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: aspnetapp-service
          servicePort: 80
```

Thanks again for your help. 🙂

**Comment by jelledruyts** [comment]
Good stuff, thanks for posting back @richeney ! Is the app running under a sub-path now (foo.com/inspectorgadget/) or on the "root" (foo.com/)? If you happen to have it running under a sub-path just wanted to verify that it works as expected (it _should_ but just never tried).

**Comment by richeney** [comment]
I tried it with the sub path as below:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: inspectorgadget-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
  - http:
      paths:
      - path: /inspectorgadget/
        backend:
          serviceName: inspectorgadget-service
          servicePort: 80
```

And I could hit the home page, but the links to the various gadgets were broken, even when I reinserted `/inspectorgadget` within the uri.

I'm using this [annotations](https://azure.github.io/application-gateway-kubernetes-ingress/annotations/) reference.
